### ISSUE TITLE
Is CDaoTabledef going to be supported in the future?

### ISSUE THREAD

**Issue by zhengzilu** [slidertom/ds#1]
Hello,
Is CDaoTabledef going to be supported in the future? Because it was often used in my MFC program.
And it looks like using your wrapper classes can easily convert Access to SQLite without changing my program.

**Comment by slidertom** [comment]
CDaoTabledef  is MFC item and support depends on the Microsoft.
Also you can look at the:
https://www.codeproject.com/Articles/1075/A-set-of-ADO-classes-version-2-20

>And it looks like using your wrapper classes can easily convert Access 
>to SQLite without changing my program.
Yes, this is the main point - possibility to use Access  and Sqlite with the 
same interface.

Migration into sqlite you can check this also:
https://github.com/arturasn/mdb2sqlite
https://github.com/arturasn/RelationshipVisualization

(I have sqlite2mdb also)

**Comment by zhengzilu** [comment]
Yes, I also found the same project to migrate the database file system sqlite2mdb which works very good. :-)
However, my main issue is that CDAO* is already obsolete. I am thinking about if I can keep my program (high level) using the CDAO* classes name unchanged, but use other interface like ODBC Cdatabase or your classes to replace the implementation of CDAO (low level). I dont know if this is a good desgin.
The reason to do so is because I want to minimize the workload of changing my program (high level) . If not, it seems that the entire program needs to be rewritten. If you have any other idea, please let me know.

I am a little bit confused in your DaoDatabaseImpl.cpp why there is still afxdao.h included to use MFC CDaoDatabase class.

**Comment by slidertom** [comment]
I use CDAO with visual studio 2019.  Main issues: CDAO is obsolete in the x64 context. 
ds library provides possibility to use mdb and sqlite with the same interface and keeping 
same feel as you would be working with the CDAO based interfaces. 
Indeed ds uses CDAO for the mdb file access. It's exist possibility to replace this with something like
https://www.codeproject.com/Articles/1075/A-set-of-ADO-classes-version-2-20
but it's not done as main point -> possibility for the easy migration from the 
mdb to the sqlite with out big changes in the code logic. After full replace (and tests) of 
mdb with sqlite you can use x64 build with out dao dependencies or use x32 build 
with disabled dao support. ds provides transitional point: use mdb and sqlite at the same 
time and provides backward compatibility for the mdb using native CDao interfaces.

ds provides:
* same interface for the mdb and sqlite
* similar interfaces as CDao classes (almost same)
* native CDAO MFC framework reuse for the mdb (no issues during transition from CDao to ds)
* open possibilities to extend library with the non MFC based interfaces for the mdb files
* json (key/document) reuse in the mdb and sqlite 
* huge code amounts exists witch do manage sqlite in case of multi user access on the shared folder
